export const ADD_PRODUCTS_TO_STORE = "ADD_PRODUCTS_TO_STORE";
export const ADD_CATEGORIES_TO_STORE = "ADD_CATEGORIES_TO_STORE";
export const ADD_CART_TO_STORE = "ADD_CART_TO_STORE";
export const EDIT_QUANTITY_ITEM = "EDIT_QUANTITY_ITEM";

